### ISSUE TITLE
Error redeploy project

### ISSUE THREAD

**Issue by bvfalcon** [OmniFish-EE/eclipse-plugin-glassfish#1]
I use this plugin with Eclipse Glassfish 6.2.5, Eclipse IDE 2023-12 and receive an error:

From Eclipse IDE log:
<summary>IllegalStateException: deploy is failing=null</summary>
<details>

```
!ENTRY org.glassfish.eclipse.tools.server 4 0 2024-01-09 13:34:24.331
!MESSAGE deploy is failing=
!STACK 0
java.lang.IllegalStateException: deploy is failing=null
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.lambda$0(GlassFishServerBehaviour.java:694)
	at org.glassfish.eclipse.tools.server.sdk.admin.ServerAdmin$CommandBuilder.get(ServerAdmin.java:137)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishDeployedDirectory(GlassFishServerBehaviour.java:695)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishModuleForGlassFish(GlassFishServerBehaviour.java:539)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishModule(GlassFishServerBehaviour.java:246)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1093)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1185)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:989)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:776)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3187)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:357)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.glassfish.eclipse.tools.server 1 1 2024-01-09 13:34:24.331
!MESSAGE GlassFish: done publishModule in 0 ms

!ENTRY org.glassfish.eclipse.tools.server 1 1 2024-01-09 13:34:24.332
!MESSAGE GlassFish: done publishModule in 0 ms

!ENTRY org.glassfish.eclipse.tools.server 1 1 2024-01-09 13:34:24.332
!MESSAGE GlassFish: done publishModule in 0 ms

!ENTRY org.glassfish.eclipse.tools.server 4 0 2024-01-09 13:34:24.338
!MESSAGE cannot Deploy APPLICATION_NAME
!STACK 0
java.lang.IllegalStateException: deploy is failing=null
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.lambda$0(GlassFishServerBehaviour.java:694)
	at org.glassfish.eclipse.tools.server.sdk.admin.ServerAdmin$CommandBuilder.get(ServerAdmin.java:137)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishDeployedDirectory(GlassFishServerBehaviour.java:695)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishModuleForGlassFish(GlassFishServerBehaviour.java:539)
	at org.glassfish.eclipse.tools.server.deploying.GlassFishServerBehaviour.publishModule(GlassFishServerBehaviour.java:246)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1093)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1185)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:989)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:776)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3187)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:357)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

</details>

From Glassfish server.log:
<summary>IllegalArgumentException:  Invalid option: hotDeploy</summary>
<details>

```
[2024-01-09T14:21:49.983+0100] [glassfish 6.2] [SEVERE] [NCLS-CORE-00003] [jakarta.enterprise.system.core] [tid: _ThreadID=64 _ThreadName=admin-listener(3)] [timeMillis: 1704806509983] [levelValue: 1000] [[
  Exception while running a command
MultiException stack 1 of 1
java.lang.IllegalArgumentException:  Invalid option: hotDeploy
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.validateParameters(CommandRunnerImpl.java:1003)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1169)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1699)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:510)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:200)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:150)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:840)
]]
```
</details>

As a work-around I turn off option "Enable the Hot Deploy mode:" in server options and this helps.

**Comment by arjantijms** [comment]
Thanks for your report. I'll take a look at it soon.

**Comment by dmatej** [comment]
Is it still happening with GlassFish 7.0.20?
